chore: add types to saveAndReturn
theopensystemslab/planx-new pull request #1202
Opened 2022-10-12 14:22 UTC by gunar

2022-10-12 14:34 UTC, gunar commented
Works on Pizza

```
root@1201:~/planx-new# docker-compose logs seed-database
Attaching to planx-new_seed-database_1
seed-database_1  | {"level":"info","msg":"Help us improve Hasura! The cli collects anonymized usage stats which\nallow us to keep improving Hasura at warp speed. To opt-out or read more,\nvisit https://hasura.io/docs/latest/graphql/core/guides/telemetry.html\n","time":"2022-10-12T14:27:59Z"}
seed-database_1  | {"level":"info","msg":"Applying seeds...","time":"2022-10-12T14:27:59Z"}
seed-database_1  | {"level":"info","msg":"Seeds planted","time":"2022-10-12T14:27:59Z"}
seed-database_1  |
seed-database_1  | > seed-database@ upsert-flows /scripts
seed-database_1  | > node --experimental-specifier-resolution=node ./upsert-production-flows
seed-database_1  |
seed-database_1  | Fetching teams and flows...
seed-database_1  | Inserting flows and teams...
seed-database_1  | Fetching published flows...
seed-database_1  | Production flows and teams inserted successfully.
root@1201:~/planx-new#
```

2022-10-12 21:12 UTC, DafyddLlyr requested changes
Thanks so much for picking this up - great to see! A few very minor comments - let me know if you have any issues and I'll be happy to take a look.

2022-10-12 21:12 UTC, DafyddLlyr commented on api.planx.uk/types.ts
> +    has_user_saved?: boolean | undefined;
I think this is a mistake - `has_user_saved` is a column on the lowcal_sessions table whilst `NotifyConfig.personalisation` represents the variables that can be passed into an email sent via Notify.

2022-10-12 21:12 UTC, DafyddLlyr commented on api.planx.uk/types.ts
> +  govUkPayment: any;
This looks like a duplicate - I think only the `govUkPayment` nested within `data` should be correct.

2022-10-13 08:11 UTC, jessicamcinchak reviewed
thanks for starting this! added a couple comments & suggetions for tweaks to type definitions, but overall looking good :+1:

2022-10-13 08:11 UTC, jessicamcinchak commented on api.planx.uk/types.ts
> +export interface LowCalSession {
Can you also please add `email: string;` & `flow_id: string;` to this type as they're required fields?

2022-10-13 08:11 UTC, jessicamcinchak commented on api.planx.uk/types.ts
> +export interface GovUKPayment {
:+1:

one question: in the proxy response of our `/pay/:localAuthority/:paymentId` API endpoint, we'll return a filtered response that is only payment_id, amount, and state - should we mark other fields as optional here to account for that?

2022-10-17 12:18 UTC, gunar commented
Thanks for the review! I think I've now addressed all the feedback :+1:

2022-10-18 08:14 UTC, DafyddLlyr approved these changes
Perfect 👌

2022-10-21 13:20 UTC, merged