fix: missing input label on feedback
theopensystemslab/planx-new pull request #2006
Opened 2023-07-26 10:58 UTC by ianjon3s

Accessibility fix: missing input label on collapsable feedback input.

PR adds an `aria-label` to the input, referencing the input button text.

![image](https://github.com/theopensystemslab/planx-new/assets/51156018/b188c19c-7a2f-4504-80d7-e028acdc38cf)

2023-07-26 11:13 UTC, DafyddLlyr requested changes
Thanks for catching this 👍 

This looks like the sort of thing that should have been caught by an a11y test. There is a test for the parent component where this is used (`editor.planx.uk/src/@planx/components/Result/Public.test.tsx`) but it looks like it's running without the button being hit (and therefore the input isn't in the DOM).

Could you please either - 
 - Improve the test case in the file referenced above, but toggle the input to display before checking for a11y violations
 - Add a test file for `CollapsibleInput`
 
The second would probably be my preference as we would be testing a smaller, simpler, component.

2023-08-01 16:15 UTC, DafyddLlyr commented
@ianjon3s Let me know if you want to pair on this or want a bit more detail on the above comment 👍

2023-08-03 13:16 UTC, DafyddLlyr approved these changes
Happy for this to be merged @ianjon3s !

Let's catch up when you're back from annual leave and pair on unit tests here 👍

2023-08-03 13:21 UTC, ianjon3s commented
Thanks @DafyddLlyr

2023-08-03 13:22 UTC, merged