fix: all roles should be able to select from `blpu_codes` table
theopensystemslab/planx-new pull request #2229
Opened 2023-09-20 17:13 UTC by jessicamcinchak

This one came up in #help-issues: when testing Doncaster FOI _not signed into the editor_, Jenna was unexpectedly being asked property type questions manually. When testing signed in, the description from the BLPU codes lookup was correctly populating automatically. 

As I understand it, even though "public" has had full select permissions all along, the client is now being instantiated using an authorised role - so this should allow the query to succeed for all public users.

2023-09-20 17:14 UTC, jessicamcinchak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Public users need to be able to query `blpu_codes` table](https://trello.com/c/BcIdUFqc/2644-public-users-need-to-be-able-to-query-blpucodes-table)

2023-09-21 07:35 UTC, jessicamcinchak commented
Switching back to draft - this is still failing with console error 
```
[GraphQL error]: Message: Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1), Location: undefined, Path: undefined
nn @ console.ts:15
```

2023-09-21 07:38 UTC, DafyddLlyr requested changes
Thanks for picking this up so quickly and troubleshooting with Jenna and August 🏅 

This will certainly work as a solution but I think it's a bit of a misdiagnosis of the underlying issue here.

In order to keep the permission set of a role as small as possible we're aiming to not have to duplicate public permissions into each role. One of the biggest wins here would be that we wouldn't have to update every role each time the permissions set for "public" is updated. There's a little bit more context on this here - https://github.com/theopensystemslab/planx-new/pull/2182#discussion_r1312254263

What should be happening - 
 - This is a public query to fetch BLPU codes, so it should be using the `publicClient` (which sets the `x-hasura-user-role = "public"` header)
 
 Why this was missed - 
  - In #2195 I updated all calls using `client.request()` but didn't think about the `useQuery()` hook 🤦 
   - `useQuery()` uses the default client used by the `<ApolloClient>` wrapper (set to the private scope)
   
How we could fix this - 
 - Decide if `ApolloClient` should use private or public clients by default (public would be safer if slightly more annoying to deal with?)
  - Update all `useQuery()` calls to have the correct client, e.g. `useQuery(MY_QUERY, { client: privateClient });`
  
Frustratingly it looks like we can only use one `ApolloProvider` per app - so we can't conveniently wrap public / private layouts with the correct provider.

2023-09-21 14:47 UTC, DafyddLlyr approved these changes

2023-09-21 18:21 UTC, merged