feat: adding new "team_settings" table to Hasura
theopensystemslab/planx-new pull request #3289
Opened 2024-06-18 17:00 UTC by RODO94

## What does this PR do?

This PR focuses on the Hasura side of adding a new ``team_settings`` table to the database. In future, this will allow users to manage their own settings for their Team, and connect to elements of the API and Editor. 

## Where to find more info?

I have been documenting some of what I'm doing here: [team_settings notion](https://www.notion.so/opensystemslab/Team-Settings-Work-9836b2122f6f43908cedf0bf9cd89953)

## Notable exclusions

I am yet to add in space for the computed field ``boundary__bbox`` but I will look to add this in during the current sprint.

2024-06-19 11:02 UTC, DafyddLlyr requested changes
A few comments to take a look at 👍 

It's a good decision not to remove the columns from the `team` table here - we can come back and tidy this up once the feature is complete.

I think there's a bit of a chicken-egg situation with the sync scripts which is causing CI to fail. Without the `team_settings` table on production, the sync script can't read from it. What this means is that we'll need to - 
 - Deploy the changes creating the table to staging and then to production
 - Then open a PR with the sync script updates which we'll also progress forward
 
You could just comment out the file in `main.sql` and we'll just comment it back in later 👍 
 
It's a known issue and not unique to this PR - we're going to need a better solution eventually here. Open to ideas!

2024-06-19 13:57 UTC, DafyddLlyr commented on hasura.planx.uk/metadata/tables.yaml
> +- table:
Yep, that's the one! Looks correct to me - you can check that the filter matches `team_themes` (and I think there may be even a way of copying directly).

2024-06-20 10:43 UTC, DafyddLlyr commented on hasura.planx.uk/metadata/tables.yaml
> +                    _eq: teamEditor
👍

2024-06-20 10:50 UTC, DafyddLlyr approved these changes

2024-06-20 10:57 UTC, merged

2024-07-05 08:43 UTC, RODO94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create `team_settings` table](https://trello.com/c/ttAMDUjk/2511-create-teamsettings-table)