[api] implement verbatim module syntax
theopensystemslab/planx-new pull request #3528
Opened 2024-08-16 20:10 UTC by freemvmt

This PR is currently serving a purpose in troubleshooting errors with Jest in #3453.

2024-08-22 09:48 UTC, DafyddLlyr reviewed
Just catching up here @freemvmt, thanks so much for the detailed write up - much appreciated.

We're currently facing a few Jest issues in the frontend also and are considering the switch to [Vitest](https://vitest.dev/). I don't want to muddy the waters too much or add another big config heavy task to your plate, but it might be worth a timeboxed investigation to see if a switch could solve a few of your issues without too much work?

2024-09-06 12:50 UTC, freemvmt commented
As per #3453, we resolved the issue with Jest which this PR was intended to help investigate by migrating our entire test suite for `api.planx.uk` to Vitest, which had immediate results!

Implementing the `verbatimModuleSyntax` module may still be a desirable change, to make our TypeScript code as explicit as possible and safeguard against any issues with per-file transpilation, but is no longer a dependency for the Microsoft single sign on work, so this is a decision we can take in the fullness of time.

2024-09-09 10:52 UTC, DafyddLlyr requested changes
I know that this was originally introduced to resolve jest pain points, but now we've resolved that with vitest we need to decide what to do here as it's no longer a strict pre-requisite.

The authority I trust on all things TypeScript [recommends using `verbatimModuleSyntax`](https://www.totaltypescript.com/tsconfig-cheat-sheet) so I'm all in favour of this change - it's more explicit and clear so let's go ahead and make this change. Especially as you've done all the groundwork here! 

Once the PR is rebased I'll be happy to approve and merge this one.

2024-09-12 15:06 UTC, DafyddLlyr approved these changes

2024-09-12 15:33 UTC, merged