refactor: Drop redundant columns from `teams` table
theopensystemslab/planx-new pull request #3636
Opened 2024-09-06 09:08 UTC by RODO94

2024-09-06 10:15 UTC, RODO94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow editors to see/update their team's submission email in "Team settings" form](https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form)

2024-09-06 10:46 UTC, jessicamcinchak reviewed
Two adjustments please! 
- Can you please squash migrations into a single `up.sql` & `down.sql` ? 
  - You can drop many columns at once on the same table like `ALTER TABLE table DROP COLUMN col1, DROP COLUMN col2;` 
- Similar to comment on #3635, the order of commands in the `down` files are not currently valid - eg need to add a column before it can be commented on, altered etc

2024-09-09 16:00 UTC, DafyddLlyr requested changes
Please also take a look at the migration files at `planx-new/hasura.planx.uk/migrations/1692010483148_add_team_boundary` - there's an orphaned `boundary_bbox()` function that should also be tidied up here now we're handling this on the frontend.

One thing to consider here - just updating db columns won't update the types directly. We'll also need a corresponding change in `planx-core` which removes these properties from the `Team` type (if they're present), and then import this type into the wider codebase to pick up any cascading changes. There is a chance that all tests are passing because types and mocks are unaware of the changes made in this PR.

2024-09-10 08:03 UTC, RODO94 commented on hasura.planx.uk/metadata/tables.yaml
> -    name: teams_summary
Sorry! That was in the submission email PR, but this is the exact same issue. Removing columns and not repointing the View creation. My bad for missing this again

2024-09-10 08:06 UTC, RODO94 commented on hasura.planx.uk/metadata/tables.yaml
> -    name: teams_summary
@DafyddLlyr for this one, if we merge my submission_email PR (#3640), I have already changed the references in the View creation, so this won't be an issue? 

Could be a nice candidate to re-do this on a clean branch once #3640 is merged and reopen a new PR?

2024-09-10 08:06 UTC, RODO94 commented on hasura.planx.uk/metadata/tables.yaml
> -    name: teams_summary
Otherwise, I would be repeating code across the migrations

2024-09-10 11:07 UTC, closed without merging