refactor: remove `submission_email` column from `teams` table
theopensystemslab/planx-new pull request #3640
Opened 2024-09-09 09:21 UTC by RODO94

# What does this PR do?

To finish the work on https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form

I have dropped the redundant column and adjusted the scripts which create the local DBs.

In order to keep the `team_summary` table, I had to adjust the sql code which creates it. From here I also repointed the `homepage` column of this table from `teams` table to `team_settings` table.

`Up` script running order: 

1. Change `team_summary` view using `team_settings.submission_email` column
2. Remove `teams.submission_email` column

`Down` script:

1. Add `teams.submission_email` column
2. Replace `team_summary` view using new column

Regression tests passing

2024-09-09 16:06 UTC, DafyddLlyr requested changes
A few small comments!

2024-09-09 16:06 UTC, DafyddLlyr commented on hasura.planx.uk/migrations/1725873202035_alter_table_public_teams_drop_column_submission_email/down.sql
> +alter table "public"."teams" alter column "submission_email" drop not null;
This line seems redundant - we're not defining a `NOT NULL` constraint when adding the column here.

2024-09-09 16:06 UTC, DafyddLlyr commented on hasura.planx.uk/migrations/1725873202035_alter_table_public_teams_drop_column_submission_email/down.sql
> +comment on column "public"."teams"."submission_email" is E'Teams are core way we organise `flows` and configure settings like theme colour, logo, and contact info; name usually reflects a council but
This comment doesn't match the column - maybe a copy/paste issue?

2024-09-09 16:06 UTC, DafyddLlyr commented on hasura.planx.uk/migrations/1725873202035_alter_table_public_teams_drop_column_submission_email/up.sql
> +    ts.submission_email AS send_to_email_address,
👍

2024-09-10 08:03 UTC, DafyddLlyr approved these changes
Perfect - thanks for making these changes!

2024-09-10 08:17 UTC, merged

2024-09-10 08:58 UTC, RODO94 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow editors to see/update their team's submission email in "Team settings" form](https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form)