refactor: split out ui file
theopensystemslab/planx-new pull request #3865
Opened 2024-10-28 17:21 UTC by jamdelion

2024-10-29 13:26 UTC, DafyddLlyr requested changes
Great little refactor, love to see it!

A few comments on co-locating the Editor modal components 👍

2024-10-29 13:26 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/InternalNotes.tsx
I think this should move to `/src/ui/editor/` to be located alongside other Editor modal components.

2024-10-29 13:26 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/MoreInformation/MoreInformation.tsx
As above, this should go in `/src/ui/editor`.

The intention here would be for `src/@planx/components` to be the _graph_ components. There's a tricky language thing here where these are the lego building blocks of the graph, but the word "component" in the lego block sense clashes with "component" in the web framework sense.

2024-10-29 13:26 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/sharedTypes.tsx
Maybe `/shared/types.tsx` would be more appropriate here?

2024-10-29 14:19 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/InternalNotes.tsx
Thanks, that makes sense! I think I've got a few holes in my understanding of the context around these groupings so that's helpful to have that framing :)

2024-10-29 14:19 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/MoreInformation/MoreInformation.tsx
I wonder if it would make sense to rename one of the folders to `graphComponents` in that case? 🤔

2024-10-30 16:39 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/MoreInformation/MoreInformation.tsx
Just discussed in dev call - let's stick with `/components` for now 👍

2024-10-30 16:40 UTC, DafyddLlyr approved these changes

2024-10-30 16:45 UTC, merged