refactor: added Int Portal restyling to Ext Portal
theopensystemslab/planx-new pull request #3998
Opened 2024-11-21 14:08 UTC by RODO94

2025-01-23 15:50 UTC, RODO94 commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +              flows.find((flow: Flow) => flow.id === formik.values.flowId) ||
Without cascading more changes, I had to pull in the id and use that to define the value of each item, so I could relate it to the team. From what I could gauge, we need to ensure the id is assigned to formik so it can be passed in for existing portals.

Happy to consider a bigger change here, but my thinking was keeping the changes isolated to this file to maintain existing functionality

2025-01-28 10:47 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.test.tsx
> +  screen.debug(autocompleteInput);
nit: screen.debug left in 🧼 🫧

2025-01-28 10:51 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.test.tsx
> +  const autocompleteComp = screen.getByTestId("flowId");
what does 'comp' mean?

2025-01-28 10:53 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
nit: Rather than growing this file with more sub-components and type definitions, could you consider splitting out into a separate `types.ts` file and `components` sub-folder? I think it makes the files much easier to read when they're just dealing with one component at a time.

2025-01-28 11:01 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +              flows.filter((flow) => {
You can write this more succinctly like this: 

```suggestion
              flows?.filter((flow) => {
```

2025-01-28 11:06 UTC, jamdelion commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +  id: string | "select a flow";
it seems a bit weird to me that `Select a flow` could be the `id` of a flow. Perhaps I'd expect to see more of a mapping where like `{id: "xyz"}` is mapped to a fallback string ("select a flow") or something?

2025-01-29 09:10 UTC, DafyddLlyr requested changes
A few comments and questions on the PR below, but a more general piece of feedback at this stage.

This one has turned out more complicated (and time consuming) than expected so I'd think that the best course of action here is to implement style changes, so that it's visually consistent with other Editor modals and not focus on the two selects and their interactions. I did think that this was the conclusion we got to in the Slack thread the other day and was expecting to see those changes implemented here - apologies if that wasn't clear though 👌 

So we'd end up with - 
 - Visually consistent and updated modal
 - A single select - this can certainly be grouped by team as you have here (if George/Jonny/August think this is an improvement) - I think it would be as we have a typeahead implemented
 - Trello ticket to gather Editor feedback / implement multiple selects with reference to these PRs so we can revisit this in future without losing design and dev work
 

Happy to talk this through if you'd like - just let me know.

2025-01-29 09:10 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +          <SelectMultiple
There's an odd interaction here - if I have a flow selected, and then change the team the fist flow of this team gets selected which is quite unexpected.

2025-01-29 09:10 UTC, DafyddLlyr commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +      <AutocompleteSubHeader
This looks quite different to other grouping we have - see `FileUploadAndLabel`

2025-01-31 12:48 UTC, RODO94 commented on editor.planx.uk/src/@planx/components/ExternalPortal/Editor.tsx
> +const renderGroup: FlowAutocompleteListProps["renderGroup"] = (params) => {
Only thing stopping this is how we handle the `freeSolo` prop in the Autocomplete type. I've done an initial bit of work in standardising some components, types, and styles and locating them somewhere shared. I'd appreciate feedback on how deep to go here, to me it does feel like another PR to merge all of our Autocomplete uses and the nuances.

2025-02-03 15:08 UTC, jamdelion commented on editor.planx.uk/src/ui/shared/Autocomplete/styles.ts
> +    // TODO extract as `format="data"` prop more like `Input` ?
Is this todo overlooked for this PR or a future thing you were going to come back to?

2025-02-03 15:11 UTC, jamdelion commented
![Screenshot 2025-02-03 at 15 10 40](https://github.com/user-attachments/assets/7b88aef7-6d44-4047-8d35-17ed8ede3b7d)

Just looked at the pizza again and functionality looks good. One thing I was thinking though is that the initial state of this input as a blank box is a bit disconcerting to me. Maybe I'd expect to see some sort of dropdown arrow in it? Or a placeholder? I feel like it needs some visual indication of what interaction is expected with it maybe...

2025-02-03 15:35 UTC, RODO94 commented
> ![Screenshot 2025-02-03 at 15 10 40](https://github.com/user-attachments/assets/7b88aef7-6d44-4047-8d35-17ed8ede3b7d)
> 
> Just looked at the pizza again and functionality looks good. One thing I was thinking though is that the initial state of this input as a blank box is a bit disconcerting to me. Maybe I'd expect to see some sort of dropdown arrow in it? Or a placeholder? I feel like it needs some visual indication of what interaction is expected with it maybe...

@jamdelion do you think a drop down arrow and maybe a more descriptive label would work? 

"Pick a flow or type to search"

2025-02-03 16:04 UTC, jamdelion approved these changes
Looking good to me!

2025-02-04 16:05 UTC, DafyddLlyr approved these changes

2025-02-04 16:17 UTC, merged